CREATE TABLESPACE springStudy
DATAFILE 'C:/cbc/oradata/springStudy.dbf'
SIZE 50m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED;

CREATE USER springStudy IDENTIFIED BY 1234
DEFAULT TABLESPACE springStudy;

GRANT CONNECT, RESOURCE TO springStudy;