CREATE TABLE member(
id VARCHAR2(50) NOT NULL,
passwd VARCHAR2(50) NOT NULL,
name VARCHAR2(50) NOT NULL,
phone VARCHAR2(50) NOT NULL,
email VARCHAR2(50) NOT NULL,
address VARCHAR2(50) NOT NULL,
regiDate DATE NOT NULL
);

CREATE TABLE product (
productCode NUMBER NOT NULL,
productName VARCHAR2(50) NOT NULL,
productPrice NUMBER NOT NULL,
productContent CLOB NOT NULL,
productCategory VARCHAR2(50) NOT NULL,
vendor VARCHAR2(50) NOT NULL,
regiDate DATE NOT NULL,
PRIMARY KEY (productCode)
);

CREATE SEQUENCE seq_product START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;