CREATE TABLESPACE jspStudyModel2
DATAFILE 'C:/cbc/oradata/jspStudyModel2.dbf'
SIZE 50m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED;

CREATE USER jspStudyModel2 IDENTIFIED BY 1234
DEFAULT TABLESPACE jspStudyModel2;

GRANT CONNECT, RESOURCE TO jspStudyModel2;
