CREATE TABLESPACE bookTest
DATAFILE 'C:/cbc/oradata/bookTest.dbf' SIZE 50m
AUTOEXTEND ON
NEXT 10m
MAXSIZE UNLIMITED;

CREATE USER booktest IDENTIFIED BY 1234
DEFAULT TABLESPACE booktest;

GRANT CONNECT, RESOURCE TO booktest;